- name: Deploy over SSH (force overwrite)
  uses: appleboy/ssh-action@v0.1.8
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    password: ${{ secrets.PASSWORD }}
    script_stop: true
    command_timeout: 10m
    script: |
      set -euo pipefail
      cd /home/realsolutions/htdocs/www.realsolutions.ai
      git fetch origin main
      git reset --hard origin/main
      # Full cleanup (blunt): deletes untracked files/dirs
      git clean -fd
      chown -R realsolutions:realsolutions .
      chmod -R 755 .
      sudo varnishadm "ban req.http.host ~ www.realsolutions.ai"
