name: Deploy to VPS (force overwrite)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (optional but nice for logs/tests)
        uses: actions/checkout@v3

      - name: Deploy over SSH (force overwrite)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          command_timeout: 10m
          script: |
            set -euo pipefail
            cd /home/realsolutions/htdocs/www.realsolutions.ai

            # Make the working tree EXACTLY match origin/main
            git fetch origin main
            git reset --hard origin/main

            # Remove all untracked AND ignored files/dirs (nukes caches, uploads, etc.)
            # Use -fdx to be thorough; switch to the "safe exclusions" variant below if needed.
            git clean -fdx

            # (Optional) reload PHP-FPM to clear opcode cache; ignore if not present
            sudo systemctl reload php-fpm || sudo systemctl reload php8.2-fpm || true

            # Permissions & cache purge
            chown -R realsolutions:realsolutions .
            chmod -R 755 .
            sudo varnishadm "ban req.http.host ~ www.realsolutions.ai"
