name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/realsolutions/htdocs/www.realsolutions.ai
          git pull origin main
          chown -R realsolutions:realsolutions .
          chmod -R 755 .
          sudo varnishadm "ban req.http.host ~ www.realsolutions.ai"
