name: Deploy to VPS (RealSolutions)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-realsolutions
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Deploy over SSH (force overwrite, safe excludes)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # Omit port to use default 22, or uncomment the next line if you set one:
          # port: ${{ secrets.PORT }}
          script_stop: true
          command_timeout: 10m
          script: |
            set -euo pipefail

            # === paths & variables ===
            SITE_DIR="/home/realsolutions/htdocs/www.realsolutions.ai"
            KEEP_CONFIG="/home/realsolutions/wp-config.php"   # server copy of wp-config.php (outside repo)
            DOMAIN="www.realsolutions.ai"

            cd "$SITE_DIR"

            # 1) One-time safety: if a config exists in the webroot, save a copy outside the repo
            if [ -f wp-config.php ] && [ ! -f "$KEEP_CONFIG" ]; then
              cp wp-config.php "$KEEP_CONFIG"
            fi

            # 2) Make the working tree EXACTLY match origin/main (code overwrite)
            git fetch origin main
            git reset --hard origin/main

            # 3) Remove all untracked/ignored files EXCEPT critical site data
            #    (keep server wp-config, uploads, htaccess, debug log)
            git clean -fdx \
              -e wp-config.php \
              -e wp-content/uploads/ \
              -e .htaccess \
              -e wp-content/debug.log

            # 4) Ensure wp-config.php exists after clean (restore from server copy if needed)
            if [ ! -f wp-config.php ] && [ -f "$KEEP_CONFIG" ]; then
              cp "$KEEP_CONFIG" wp-config.php
            fi

            # 5) Permissions
            if [ -d wp-content ]; then
              find wp-content -type d -exec chmod 775 {} \;
              find wp-content -type f -exec chmod 664 {} \;
            fi

            if [ -f wp-config.php ]; then
              chmod 640 wp-config.php
              if getent group clp >/dev/null 2>&1; then chgrp clp wp-config.php || true; fi
            fi

            chown -R realsolutions:realsolutions .
            find . -type d -not -path "./wp-content/*" -exec chmod 755 {} \;
            find . -type f -not -path "./wp-content/*" -not -name "wp-config.php" -exec chmod 644 {} \;

            # 6) Opcache / service reloads (best-effort)
            sudo systemctl reload php8.1-fpm || sudo systemctl reload php-fpm || true
            sudo systemctl reload nginx || true

            # 7) Purge Varnish (best-effort)
            sudo varnishadm "ban req.http.host ~ ${DOMAIN}" || true
