name: Deploy to VPS

on:
  push:
    branches: [ main ]  # Triggers when you push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PASSWORD }}
        script: |
          cd /home/realsolutions/htdocs/www.realsolutions.ai
          git pull origin main
          chown -R realsolutions:realsolutions .
          chmod -R 755 .
          # Clear any caches if needed
          # wp cache flush (if you have WP-CLI)
